# Generated by Django 4.2.4 on 2024-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FashionFusionApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("image", models.ImageField(upload_to="static/img/products")),
            ],
        ),
    ]
