# Generated by Django 4.2.4 on 2024-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FashionFusionApp", "0002_productstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="pharmacyStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ganeric_name", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("available_stock", models.IntegerField()),
                ("expiry_date", models.DateField()),
            ],
        ),
    ]
