# Generated by Django 4.2.4 on 2024-05-22 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FashionFusionApp", "0003_pharmacystock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="pharmacyStock",
        ),
    ]
